app:
  database: bibliotek.db
  bucket: bibliotek-test
  schema: schema.sql
  port: 5678

storage:
  aws_access_key_id: ${AWS_ACCESS_KEY_ID}
  aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  aws_endpoint_url_s3: ${AWS_ENDPOINT_URL_S3:-https://t3.storage.dev}
  aws_endpoint_url_iam: ${AWS_ENDPOINT_URL_IAM:-https://iam.storage.dev}
  aws_region: ${AWS_REGION:-auto}
  service: ${SERVICE:-t3}
